# Site settings
title: Infrequent Rambling
description: > # Stuff that's spilled out of my head over the last decade or so
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.infrequentrambling.net" # the base hostname & protocol for your site
twitter_username: paulbailey

# Build settings
markdown: kramdown

permalink: :title.html

include:
  - .nojekyll

exclude:
  - "Rakefile"
